sudo: required
services: 
    - docker

before_install: 
  - docker build -t itstefone/docker-react -f Dockerfile.dev .

script: 
  - docker run itstefone/docker-react npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    access_key_id:
      secure: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
    region: "eu-central-1"
    app: "Docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-central-1-641874005858"
    bucket_path: "Docker"
    on: 
      branch: master